import { WEATHER_CODE } from '~/types/weatherCode';

export const weatherByCode = {
  [WEATHER_CODE.TORNADO]: 'Tornado',
  [WEATHER_CODE.TROPICAL_STORM]: 'Tropical Storm',
  [WEATHER_CODE.HURRICANE]: 'Hurricane',
  [WEATHER_CODE.SEVERE_THUNDERSTORMS]: 'Severe Thunderstorms',
  [WEATHER_CODE.THUNDERSTORMS]: 'Thunderstorms',
  [WEATHER_CODE.MIXED_RAIN_AND_SNOW]: 'Mixed Rain and Snow',
  [WEATHER_CODE.MIXED_RAIN_AND_SLEET]: 'Mixed Rain and Sleet',
  [WEATHER_CODE.MIXED_SNOW_AND_SLEET]: 'Mixed Snow and Sleet',
  [WEATHER_CODE.FREEZING_DRIZZLE]: 'Freezing Drizzle',
  [WEATHER_CODE.DRIZZLE]: 'Drizzle',
  [WEATHER_CODE.FREEZING_RAIN]: 'Freezing Rain',
  [WEATHER_CODE.SHOWERS]: 'Showers',
  [WEATHER_CODE.HEAVY_SHOWERS]: 'Heavy Showers',
  [WEATHER_CODE.SNOW_FLURRIES]: 'Snow Flurries',
  [WEATHER_CODE.LIGHT_SNOW_SHOWERS]: 'Light Snow Showers',
  [WEATHER_CODE.BLOWING_SNOW]: 'Blowing Snow',
  [WEATHER_CODE.SNOW]: 'Snow',
  [WEATHER_CODE.HAIL]: 'Hail',
  [WEATHER_CODE.SLEET]: 'Sleet',
  [WEATHER_CODE.DUST]: 'Dust',
  [WEATHER_CODE.FOGGY]: 'Foggy',
  [WEATHER_CODE.HAZE]: 'Haze',
  [WEATHER_CODE.SMOKY]: 'Smoky',
  [WEATHER_CODE.BLUSTERY]: 'Blustery',
  [WEATHER_CODE.WINDY]: 'Windy',
  [WEATHER_CODE.COLD]: 'Cold',
  [WEATHER_CODE.CLOUDY]: 'Cloudy',
  [WEATHER_CODE.MOSTLY_CLOUDY_NIGHT]: 'Mostly Cloudy (night)',
  [WEATHER_CODE.MOSTLY_CLOUDY_DAY]: 'Mostly Cloudy (day)',
  [WEATHER_CODE.PARTLY_CLOUDY_NIGHT]: 'Partly Cloudy (night)',
  [WEATHER_CODE.PARTLY_CLOUDY_DAY]: 'Partly Cloudy (day)',
  [WEATHER_CODE.CLEAR_NIGHT]: 'Clear (night)',
  [WEATHER_CODE.SUNNY]: 'Sunny',
  [WEATHER_CODE.FAIR_NIGHT]: 'Fair (night)',
  [WEATHER_CODE.FAIR_DAY]: 'Fair (day)',
  [WEATHER_CODE.MIXED_RAIN_AND_HAIL]: 'Mixed Rain and Hail',
  [WEATHER_CODE.HOT]: 'Mixed Rain and Hail',
  [WEATHER_CODE.ISOLATED_THUNDERSTORMS]: 'Isolated Thunderstorms',
  [WEATHER_CODE.SCATTERED_THUNDERSTORMS_38]: 'Scatted Thunderstorms',
  [WEATHER_CODE.SCATTERED_THUNDERSTORMS_39]: 'Scatted Thunderstorms',
  [WEATHER_CODE.SCATTERED_SHOWERS]: 'Scatted Showers',
  [WEATHER_CODE.HEAVY_SNOW_41]: 'Heavy Snow',
  [WEATHER_CODE.SCATTERED_SNOW_SHOWERS]: 'Scattered Snow Showers',
  [WEATHER_CODE.HEAVY_SNOW_43]: 'Heavy Snow',
  [WEATHER_CODE.PARTLY_CLOUDY]: 'Partly Cloudy',
  [WEATHER_CODE.THUNDERSHOWERS]: 'Thundershowers',
  [WEATHER_CODE.SNOW_SHOWERS]: 'Snow Showers',
  [WEATHER_CODE.ISOLATED_THUNDERSHOWERS]: 'Isolated Thundershowers',
  [WEATHER_CODE.NOT_AVAILABLE]: 'Not Available',
};
